module.exports = {
    MAX_ATTEMPTS: 3,
    VOTE_ADDED: 'VOTE_ADDED',
    STS_TOKEN: 'STS_TOKEN',
    NO_FACE_FOUND: 'NO_FACE_FOUND',
    NO_EMAIL_FOUND: 'NO_EMAIL_FOUND',
    FACE_ALREADY_ADDED: 'FACE_ALREADY_ADDED',
    ERROR_INDEXING_FACE: 'ERROR_INDEXING_FACE',
    NO_FACE_DETECTED_IN_PHOTO: 'NO_FACE_DETECTED_IN_PHOTO'
}